// <auto-generated />
using System;
using BackendService.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendService.Data.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260509212545_UpdateInvoiceAndSeedData")]
    partial class UpdateInvoiceAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendService.Model.Common.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            TenDanhMuc = "Điện thoại",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            TenDanhMuc = "Laptop",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            TenDanhMuc = "Máy tính bảng",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            TenDanhMuc = "Phụ kiện",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            TenDanhMuc = "Đồng hồ",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendService.Model.DonViTinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DonViTinhs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Đơn vị tính cơ bản",
                            TenDonViTinh = "Cái",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendService.Model.EmployeeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Identify")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EmployeeProfiles", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Imports", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.ImportDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImportDetails", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InvoiceItems", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DonViTinhId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cost = 8000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho iPhone 15 Pro Max",
                            DiscountPrice = 9000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 10000000m,
                            ProductName = "iPhone 15 Pro Max",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cost = 8500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Samsung Galaxy S24 Ultra",
                            DiscountPrice = 9500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 10500000m,
                            ProductName = "Samsung Galaxy S24 Ultra",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cost = 9000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Google Pixel 8 Pro",
                            DiscountPrice = 10000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 11000000m,
                            ProductName = "Google Pixel 8 Pro",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cost = 9500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Xiaomi 14 Ultra",
                            DiscountPrice = 10500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 11500000m,
                            ProductName = "Xiaomi 14 Ultra",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cost = 10000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Oppo Find X7 Ultra",
                            DiscountPrice = 11000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 12000000m,
                            ProductName = "Oppo Find X7 Ultra",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cost = 10500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho MacBook Pro M3",
                            DiscountPrice = 11500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 12500000m,
                            ProductName = "MacBook Pro M3",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cost = 11000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Dell XPS 15",
                            DiscountPrice = 12000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 13000000m,
                            ProductName = "Dell XPS 15",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cost = 11500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho HP Spectre x360",
                            DiscountPrice = 12500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 13500000m,
                            ProductName = "HP Spectre x360",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cost = 12000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Asus ROG Zephyrus G14",
                            DiscountPrice = 13000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 14000000m,
                            ProductName = "Asus ROG Zephyrus G14",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cost = 12500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Lenovo ThinkPad X1 Carbon",
                            DiscountPrice = 13500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 14500000m,
                            ProductName = "Lenovo ThinkPad X1 Carbon",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cost = 13000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho iPad Pro M2",
                            DiscountPrice = 14000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 15000000m,
                            ProductName = "iPad Pro M2",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cost = 13500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Samsung Galaxy Tab S9",
                            DiscountPrice = 14500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 15500000m,
                            ProductName = "Samsung Galaxy Tab S9",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cost = 14000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Surface Pro 9",
                            DiscountPrice = 15000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 16000000m,
                            ProductName = "Surface Pro 9",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cost = 14500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Xiaomi Pad 6",
                            DiscountPrice = 15500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 16500000m,
                            ProductName = "Xiaomi Pad 6",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cost = 15000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Lenovo Tab P12",
                            DiscountPrice = 16000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 17000000m,
                            ProductName = "Lenovo Tab P12",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cost = 15500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho AirPods Pro 2",
                            DiscountPrice = 16500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 17500000m,
                            ProductName = "AirPods Pro 2",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cost = 16000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Sony WH-1000XM5",
                            DiscountPrice = 17000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 18000000m,
                            ProductName = "Sony WH-1000XM5",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cost = 16500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Samsung Galaxy Buds2 Pro",
                            DiscountPrice = 17500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 18500000m,
                            ProductName = "Samsung Galaxy Buds2 Pro",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cost = 17000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Logitech MX Master 3S",
                            DiscountPrice = 18000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 19000000m,
                            ProductName = "Logitech MX Master 3S",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cost = 17500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Razer DeathAdder V3",
                            DiscountPrice = 18500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 19500000m,
                            ProductName = "Razer DeathAdder V3",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cost = 18000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Apple Watch Series 9",
                            DiscountPrice = 19000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 20000000m,
                            ProductName = "Apple Watch Series 9",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cost = 18500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Samsung Galaxy Watch 6",
                            DiscountPrice = 19500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 20500000m,
                            ProductName = "Samsung Galaxy Watch 6",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cost = 19000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Garmin Fenix 7",
                            DiscountPrice = 20000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 21000000m,
                            ProductName = "Garmin Fenix 7",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cost = 19500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Huawei Watch GT 4",
                            DiscountPrice = 20500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 21500000m,
                            ProductName = "Huawei Watch GT 4",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cost = 20000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Amazfit GTR 4",
                            DiscountPrice = 21000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 22000000m,
                            ProductName = "Amazfit GTR 4",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cost = 20500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho iPhone 14",
                            DiscountPrice = 21500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 22500000m,
                            ProductName = "iPhone 14",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cost = 21000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Samsung Galaxy A54",
                            DiscountPrice = 22000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 23000000m,
                            ProductName = "Samsung Galaxy A54",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cost = 21500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho MacBook Air M2",
                            DiscountPrice = 22500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 23500000m,
                            ProductName = "MacBook Air M2",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cost = 22000000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho iPad Air 5",
                            DiscountPrice = 23000000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 24000000m,
                            ProductName = "iPad Air 5",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cost = 22500000m,
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Description = "Mô tả cho Sony WF-1000XM5",
                            DiscountPrice = 23500000m,
                            DonViTinhId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Image_Url = "https://picsum.photos/200/300",
                            Price = 24500000m,
                            ProductName = "Sony WF-1000XM5",
                            Status = 2,
                            SupplierId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendService.Model.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Identify")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Hà Nội",
                            CreatedBy = "",
                            CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeleteFlag = false,
                            Email = "contact@tongkho.com",
                            Identify = 123456,
                            PhoneNumber = 123456789,
                            SupplierName = "Tổng kho điện máy",
                            UpdatedBy = "",
                            UpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendService.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BackendService.Model.Product", b =>
                {
                    b.HasOne("BackendService.Model.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");
                });
#pragma warning restore 612, 618
        }
    }
}
